[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pygip*"]  # IMPORTANT: includes pygip, pygip.models, pygip.models.attack, etc.
