from __future__ import annotations

import inspect
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Literal, Mapping, Optional, Sequence, Set

import torch
import yaml
from pydantic import BaseModel, Field, model_validator


REPO_ROOT = Path(__file__).resolve().parent.parent
MODEL_CARDS_DIR = Path(__file__).resolve().parent / "model_cards"
DOCS_SOURCE_DIR = REPO_ROOT / "docs" / "source"
MODULE_DOCS_DIR = DOCS_SOURCE_DIR / "modules"
MODEL_PAGE_PATH = DOCS_SOURCE_DIR / "pyhazards_models.rst"
API_PAGE_PATH = DOCS_SOURCE_DIR / "api" / "pyhazards.models.rst"

GENERATED_MARKER = (
    ".. This file is generated by scripts/render_model_docs.py. Do not edit by hand."
)
MODEL_PR_MARKER = "<!-- pyhazards:model-pr -->"
MODEL_REVIEW_MARKER = "<!-- pyhazards:model-pr-review -->"

NON_CATALOG_MODELS = {
    "mlp",
    "cnn",
    "temporal",
}

HAZARD_DISPLAY_ORDER = [
    "Wildfire",
    "Earthquake",
    "Flood",
    "Tropical Cyclone",
]

NORMALIZED_HAZARD_LABELS = {
    "Hurricane": "Tropical Cyclone",
}

CATALOG_STATUS_ORDER = [
    "core",
    "variant",
    "experimental",
]

IMPLEMENTED_SECTION_TITLE = "Implemented Models"
IMPLEMENTED_SECTION_SUMMARY = (
    "This table includes both core baselines and public variants or additional "
    "implementations for the hazard family."
)
EXPERIMENTAL_SECTION_TITLE = "Experimental Adapters"
EXPERIMENTAL_SECTION_SUMMARY = (
    "These entries remain public as lightweight wrapper or prototype integrations "
    "and should not be counted as stable implemented methods."
)

HAZARD_SECTION_SUMMARIES = {
    "Wildfire": (
        "Wildfire models cover danger forecasting, weekly activity forecasting, "
        "and spread prediction under the shared wildfire benchmark family."
    ),
    "Earthquake": (
        "Earthquake models span phase picking and dense-grid forecasting, with "
        "detail pages linked to the shared earthquake benchmark coverage."
    ),
    "Flood": (
        "Flood models cover streamflow and inundation forecasting, ranging from "
        "sequence baselines to dense-grid flood-mapping architectures."
    ),
    "Tropical Cyclone": (
        "Storm models are organized under one tropical-cyclone family, including "
        "basin-specific hurricane baselines and shared all-basin forecasting models."
    ),
}

TASK_DISPLAY_LABELS = {
    "wildfire.danger": "Danger",
    "wildfire.spread": "Spread",
    "earthquake.picking": "Phase Picking",
    "earthquake.forecasting": "Wavefield Forecasting",
    "flood.streamflow": "Streamflow",
    "flood.inundation": "Inundation",
    "tc.track_intensity": "Track + Intensity",
    "classification": "Classification",
    "regression": "Forecasting",
    "segmentation": "Segmentation",
}

MATURITY_LABELS = {
    "core": "Implemented",
    "variant": "Implemented",
    "experimental": "Experimental Adapter",
    "hidden": "Hidden",
}

MATURITY_BADGE_ROLES = {
    "core": "success",
    "variant": "success",
    "experimental": "warning",
    "hidden": "secondary",
}

STARTER_MODELS = {
    "Wildfire": "firecastnet",
    "Earthquake": "phasenet",
    "Flood": "floodcast",
    "Tropical Cyclone": "hurricast",
}


class PaperReference(BaseModel):
    title: str
    url: str
    repo_url: Optional[str] = None


class SmokeTensorSpec(BaseModel):
    shape: List[int]
    dtype: str = "float32"


class SmokeInputSpec(BaseModel):
    kind: str
    tensor: Optional[SmokeTensorSpec] = None
    mapping: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)
    kwargs: Dict[str, SmokeTensorSpec] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeInputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.tensor is None:
            raise ValueError("tensor smoke inputs require the 'tensor' field")
        if kind == "mapping" and not self.mapping:
            raise ValueError("mapping smoke inputs require the 'mapping' field")
        if kind == "kwargs" and not self.kwargs:
            raise ValueError("kwargs smoke inputs require the 'kwargs' field")
        if kind not in {"tensor", "mapping", "kwargs"}:
            raise ValueError("smoke input kind must be one of: tensor, mapping, kwargs")
        return self


class SmokeOutputSpec(BaseModel):
    kind: str = "tensor"
    shape: Optional[List[int]] = None
    shapes: List[List[int]] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_payload(self) -> "SmokeOutputSpec":
        kind = self.kind.lower()
        if kind == "tensor" and self.shape is None:
            raise ValueError("tensor smoke outputs require the 'shape' field")
        if kind == "sequence" and not self.shapes:
            raise ValueError("sequence smoke outputs require the 'shapes' field")
        if kind not in {"tensor", "sequence"}:
            raise ValueError("smoke output kind must be one of: tensor, sequence")
        return self


class SmokeTestSpec(BaseModel):
    task: str
    build_kwargs: Dict[str, Any] = Field(default_factory=dict)
    input: SmokeInputSpec
    expected_output: SmokeOutputSpec


class ModelCard(BaseModel):
    model_name: str
    display_name: str
    hazard: str
    include_in_public_catalog: bool = True
    catalog_status: Literal["core", "variant", "experimental", "hidden"] = "core"
    family_key: Optional[str] = None
    family_label: Optional[str] = None
    source_file: str
    builder_name: str
    summary: str
    description: List[str]
    paper: PaperReference
    tasks: List[str]
    example: str
    notes: List[str] = Field(default_factory=list)
    aliases: List[str] = Field(default_factory=list)
    doc_slug: Optional[str] = None
    smoke_test: SmokeTestSpec

    @model_validator(mode="after")
    def validate_catalog_metadata(self) -> "ModelCard":
        if self.catalog_status == "hidden" and self.include_in_public_catalog:
            raise ValueError("hidden catalog_status requires include_in_public_catalog: false")
        if self.family_key and not self.family_label:
            raise ValueError("family_key requires family_label")
        if self.family_label and not self.family_key:
            raise ValueError("family_label requires family_key")
        return self

    @property
    def registry_names(self) -> List[str]:
        return [self.model_name] + list(self.aliases)

    @property
    def module_doc_name(self) -> str:
        return self.doc_slug or "models_{name}".format(name=self.model_name)

    @property
    def module_doc_path(self) -> Path:
        return MODULE_DOCS_DIR / "{name}.rst".format(name=self.module_doc_name)

    @property
    def source_path(self) -> Path:
        return REPO_ROOT / self.source_file


def load_model_cards(cards_dir: Path = MODEL_CARDS_DIR) -> List[ModelCard]:
    cards: List[ModelCard] = []
    seen_registry_names: Set[str] = set()
    for path in sorted(cards_dir.glob("*.y*ml")):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        card = ModelCard.model_validate(raw)
        if path.stem != card.model_name:
            raise ValueError(
                "Model card filename must match model_name: "
                "{path} vs {name}".format(path=path.name, name=card.model_name)
            )
        overlap = set(card.registry_names) & seen_registry_names
        if overlap:
            raise ValueError(
                "Duplicate model catalog names detected: {names}".format(
                    names=", ".join(sorted(overlap))
                )
            )
        seen_registry_names.update(card.registry_names)
        cards.append(card)
    return cards


def card_by_registry_name(cards: Sequence[ModelCard]) -> Dict[str, ModelCard]:
    mapping: Dict[str, ModelCard] = {}
    for card in cards:
        for name in card.registry_names:
            mapping[name] = card
    return mapping


def group_cards_by_hazard(cards: Sequence[ModelCard]) -> Dict[str, List[ModelCard]]:
    grouped: Dict[str, List[ModelCard]] = defaultdict(list)
    for card in cards:
        grouped[_display_hazard_label(card.hazard)].append(card)

    def order_key(hazard: str) -> tuple[int, str]:
        if hazard in HAZARD_DISPLAY_ORDER:
            return (HAZARD_DISPLAY_ORDER.index(hazard), hazard.lower())
        return (len(HAZARD_DISPLAY_ORDER), hazard.lower())

    return {
        hazard: sorted(hazard_cards, key=lambda item: item.display_name.lower())
        for hazard, hazard_cards in sorted(grouped.items(), key=lambda item: order_key(item[0]))
    }


def public_catalog_cards(cards: Sequence[ModelCard]) -> List[ModelCard]:
    return [card for card in cards if card.include_in_public_catalog]


def _cards_by_status(cards: Sequence[ModelCard]) -> Dict[str, List[ModelCard]]:
    grouped: Dict[str, List[ModelCard]] = {status: [] for status in CATALOG_STATUS_ORDER}
    for card in cards:
        if card.catalog_status in grouped:
            grouped[card.catalog_status].append(card)
    for status in grouped:
        grouped[status] = sorted(grouped[status], key=lambda item: item.display_name.lower())
    return grouped


def _grouped_catalog_entries(cards: Sequence[ModelCard]) -> List[List[ModelCard]]:
    entries: List[List[ModelCard]] = []
    family_seen: Set[str] = set()
    ordered_cards = sorted(cards, key=lambda item: item.display_name.lower())
    for card in ordered_cards:
        if card.family_key:
            if card.family_key in family_seen:
                continue
            family_seen.add(card.family_key)
            family_cards = [
                member
                for member in ordered_cards
                if member.family_key == card.family_key
            ]
            entries.append(family_cards)
            continue
        entries.append([card])
    return entries


def _paper_sentence(card: ModelCard) -> str:
    sentence = "`{title} <{url}>`_".format(
        title=card.paper.title,
        url=card.paper.url,
    )
    if card.paper.repo_url:
        sentence += " (`repo <{url}>`__)".format(url=card.paper.repo_url)
    return sentence + "."


def _single_line(text: str) -> str:
    return " ".join(text.split())


def _indent_block(text: str, prefix: str = "   ") -> str:
    lines = text.rstrip().splitlines()
    return "\n".join(prefix + line if line else prefix.rstrip() for line in lines)


def _indent_lines(lines: Sequence[str], prefix: str = "   ") -> List[str]:
    return [prefix + line if line else "" for line in lines]


def _display_hazard_label(hazard: str) -> str:
    return NORMALIZED_HAZARD_LABELS.get(hazard, hazard)


def _badge(role: str, text: str) -> str:
    return f":bdg-{role}:`{text}`"


def _task_display_labels(tasks: Sequence[str]) -> List[str]:
    labels = []
    seen: Set[str] = set()
    for task in tasks:
        label = TASK_DISPLAY_LABELS.get(task, task.replace("_", " ").title())
        if label not in seen:
            labels.append(label)
            seen.add(label)
    return labels


def _ordered_unique(items: Iterable[str]) -> List[str]:
    seen: Set[str] = set()
    ordered: List[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        ordered.append(item)
    return ordered


def _doc_link(card: ModelCard, absolute: bool = False) -> str:
    target = "/modules/{slug}".format(slug=card.module_doc_name) if absolute else "modules/{slug}".format(slug=card.module_doc_name)
    return ":doc:`{name} <{target}>`".format(
        name=card.display_name,
        target=target,
    )


def _benchmark_link(slug: str, display_name: str, absolute: bool = False) -> str:
    target = f"/benchmarks/{slug}" if absolute else f"benchmarks/{slug}"
    return f":doc:`{display_name} <{target}>`"


def _paper_links(card: ModelCard) -> str:
    links = [f"**Paper:** `{card.paper.title} <{card.paper.url}>`_"]
    if card.paper.repo_url:
        links.append(f"**Repo:** `Repository <{card.paper.repo_url}>`__")
    return " | ".join(links)


def _benchmark_links_by_model() -> Dict[str, Dict[str, Any]]:
    from .benchmark_catalog import load_benchmark_cards

    mapping: Dict[str, Dict[str, Any]] = {}
    for benchmark_card in load_benchmark_cards():
        for model_name in benchmark_card.linked_models:
            entry = mapping.setdefault(
                model_name,
                {
                    "family": None,
                    "ecosystems": [],
                    "tasks": [],
                },
            )
            if benchmark_card.kind == "family":
                entry["family"] = benchmark_card
            else:
                entry["ecosystems"].append(benchmark_card)
            entry["tasks"].extend(benchmark_card.tasks)

    for entry in mapping.values():
        entry["tasks"] = _ordered_unique(entry["tasks"])
        entry["ecosystems"] = sorted(
            entry["ecosystems"],
            key=lambda item: item.display_name.lower(),
        )
    return mapping


def _family_row_name(cards: Sequence[ModelCard]) -> str:
    label = cards[0].family_label or cards[0].display_name
    return label


def _family_row_summary(cards: Sequence[ModelCard], status: str, absolute_links: bool = False) -> str:
    members = ", ".join(
        _doc_link(card, absolute=absolute_links)
        for card in cards
    )
    if status == "variant":
        prefix = (
            "Family variants: {members}. These entries come from the same source "
            "paper and are grouped here so they do not count as separate core "
            "methods."
        )
    else:
        prefix = "Family members: {members}."
    return "{prefix} {paper}".format(
        prefix=prefix.format(members=members),
        paper=_paper_sentence(cards[0]),
    )


def _row_name(cards: Sequence[ModelCard]) -> str:
    if len(cards) == 1:
        return _doc_link(cards[0])
    return _family_row_name(cards)


def _row_summary(cards: Sequence[ModelCard], status: str, absolute_links: bool = False) -> str:
    if len(cards) == 1:
        card = cards[0]
        return "{summary} {paper}".format(
            summary=_single_line(card.summary).rstrip(".") + ".",
            paper=_paper_sentence(card),
        )
    return _family_row_summary(cards, status, absolute_links=absolute_links)


def _stat_card(title: str, value: str, note: str) -> List[str]:
    return [
        ".. grid-item-card:: {title}".format(title=title),
        "   :class-card: catalog-stat-card",
        "",
        "   .. container:: catalog-stat-value",
        "",
        "      {value}".format(value=value),
        "",
        "   .. container:: catalog-stat-note",
        "",
        "      {note}".format(note=note),
        "",
    ]


def _entry_task_labels(card: ModelCard, benchmark_links: Dict[str, Dict[str, Any]]) -> List[str]:
    entry = benchmark_links.get(card.model_name)
    ecosystems = entry.get("ecosystems") if entry else []
    ecosystem_tasks = [
        task
        for ecosystem in ecosystems
        for task in ecosystem.tasks
    ]
    if ecosystem_tasks:
        return _task_display_labels(_ordered_unique(ecosystem_tasks))
    return _task_display_labels(card.tasks)


def _entry_benchmark_family(card: ModelCard, benchmark_links: Dict[str, Dict[str, Any]], absolute: bool = False) -> Optional[str]:
    entry = benchmark_links.get(card.model_name)
    family = entry.get("family") if entry else None
    if family is None:
        return None
    return _benchmark_link(family.slug, family.display_name, absolute=absolute)


def _entry_ecosystem_links(card: ModelCard, benchmark_links: Dict[str, Dict[str, Any]], absolute: bool = False) -> List[str]:
    entry = benchmark_links.get(card.model_name)
    ecosystems = entry.get("ecosystems") if entry else []
    return [
        _benchmark_link(ecosystem.slug, ecosystem.display_name, absolute=absolute)
        for ecosystem in ecosystems
    ]


def _render_model_card(card: ModelCard, benchmark_links: Dict[str, Dict[str, Any]], absolute: bool = False) -> List[str]:
    maturity_label = MATURITY_LABELS[card.catalog_status]
    maturity_role = MATURITY_BADGE_ROLES[card.catalog_status]
    task_badges = " ".join(
        _badge("secondary", label)
        for label in _entry_task_labels(card, benchmark_links)
    )
    hazard_badge = _badge("primary", _display_hazard_label(card.hazard))
    maturity_badge = _badge(maturity_role, maturity_label)
    benchmark_family = _entry_benchmark_family(card, benchmark_links, absolute=absolute)
    ecosystems = _entry_ecosystem_links(card, benchmark_links, absolute=absolute)
    detail_link = _doc_link(card, absolute=absolute)

    lines = [
        ".. grid-item-card:: {title}".format(title=card.display_name),
        "   :class-card: catalog-entry-card",
        "",
        "   .. container:: catalog-entry-summary",
        "",
        "      {summary}".format(summary=_single_line(card.summary).rstrip(".") + "."),
        "",
        "   .. container:: catalog-chip-row",
        "",
        "      {chips}".format(
            chips=" ".join(
                chip for chip in [hazard_badge, task_badges, maturity_badge] if chip
            )
        ),
        "",
        "   .. container:: catalog-meta-row",
        "",
        "      **Details:** {detail}".format(detail=detail_link),
        "",
    ]

    if benchmark_family:
        lines.extend(
            [
                "   .. container:: catalog-meta-row",
                "",
                "      **Benchmark Family:** {link}".format(link=benchmark_family),
                "",
            ]
        )
    if ecosystems:
        lines.extend(
            [
                "   .. container:: catalog-meta-row",
                "",
                "      **Benchmark Ecosystems:** {links}".format(
                    links=", ".join(ecosystems),
                ),
                "",
            ]
        )

    lines.extend(
        [
            "   .. container:: catalog-link-row",
            "",
            "      {links}".format(links=_paper_links(card)),
            "",
        ]
    )
    return lines


def _render_model_grid(cards: Sequence[ModelCard], benchmark_links: Dict[str, Dict[str, Any]], absolute: bool = False) -> List[str]:
    lines: List[str] = [
        ".. grid:: 1 1 2 2",
        "   :gutter: 2",
        "   :class-container: catalog-grid",
        "",
    ]
    for card in cards:
        lines.extend(_indent_lines(_render_model_card(card, benchmark_links, absolute=absolute)))
    return lines


def _render_recommended_grid(cards: Sequence[ModelCard], benchmark_links: Dict[str, Dict[str, Any]]) -> List[str]:
    by_name = {card.model_name: card for card in cards}
    lines: List[str] = [
        ".. grid:: 1 1 2 4",
        "   :gutter: 2",
        "   :class-container: catalog-recommend-grid",
        "",
    ]
    for hazard in HAZARD_DISPLAY_ORDER:
        model_name = STARTER_MODELS.get(hazard)
        card = by_name.get(model_name) if model_name else None
        if card is None:
            continue
        benchmark_family = _entry_benchmark_family(card, benchmark_links)
        note = _single_line(card.summary).rstrip(".") + "."
        lines.extend(
            _indent_lines(
                [
                    ".. grid-item-card:: {hazard}".format(hazard=hazard),
                    "   :class-card: catalog-detail-card",
                    "",
                    "   **Start with:** {detail}".format(detail=_doc_link(card)),
                    "",
                    "   {note}".format(note=note),
                    "",
                    (
                        "   **Benchmark:** {benchmark}".format(benchmark=benchmark_family)
                        if benchmark_family
                        else "   **Benchmark:** See the model detail page for compatible benchmark coverage."
                    ),
                    "",
                ]
            )
        )
    return lines


def render_model_page(cards: Sequence[ModelCard]) -> str:
    public_cards = public_catalog_cards(cards)
    grouped = group_cards_by_hazard(public_cards)
    benchmark_links = _benchmark_links_by_model()
    implemented_cards = [
        card for card in public_cards if card.catalog_status in {"core", "variant"}
    ]
    experimental_cards = [
        card for card in public_cards if card.catalog_status == "experimental"
    ]
    benchmark_linked_count = len(
        [card for card in public_cards if card.model_name in benchmark_links]
    )

    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "Models",
        "===================",
        "",
        "Browse PyHazards model implementations across hazard families, compare",
        "scope and maturity, and navigate to model-specific detail pages.",
        "",
        "At a Glance",
        "-----------",
        "",
        ".. grid:: 1 2 4 4",
        "   :gutter: 2",
        "   :class-container: catalog-grid",
        "",
    ]
    lines.extend(
        _indent_lines(
            _stat_card(
                "Hazard Families",
                str(len(grouped)),
                "Catalog tabs grouped by the normalized public hazard taxonomy.",
            )
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card(
                "Implemented Models",
                str(len(implemented_cards)),
                "Public core baselines plus additional implemented variants.",
            )
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card(
                "Experimental Adapters",
                str(len(experimental_cards)),
                "Prototype weather-model integrations kept separate from the stable catalog.",
            )
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card(
                "Benchmark-linked Models",
                str(benchmark_linked_count),
                "Models with explicit benchmark-family or ecosystem links on this page.",
            )
        )
    )

    lines.extend(
        [
            "",
            "Catalog by Hazard",
            "-----------------",
            "",
            "Use the hazard tabs below to browse the public catalog. Each card keeps",
            "the index-page summary short, then links into model-specific detail",
            "pages and compatible benchmark coverage.",
            "",
            ".. tab-set::",
            "   :class: catalog-tabs",
            "",
        ]
    )

    for hazard, hazard_cards in grouped.items():
        cards_by_status = _cards_by_status(hazard_cards)
        implemented = cards_by_status["core"] + cards_by_status["variant"]
        experimental = cards_by_status["experimental"]
        tab_lines: List[str] = [
            ".. tab-item:: {hazard}".format(hazard=hazard),
            "",
            "   .. container:: catalog-section-note",
            "",
            "      {summary}".format(summary=HAZARD_SECTION_SUMMARIES[hazard]),
            "",
            "   .. rubric:: {title}".format(title=IMPLEMENTED_SECTION_TITLE),
            "",
            "   .. container:: catalog-section-note",
            "",
            "      {summary}".format(summary=IMPLEMENTED_SECTION_SUMMARY),
            "",
        ]
        if implemented:
            tab_lines.extend(_indent_lines(_render_model_grid(implemented, benchmark_links)))
        else:
            tab_lines.extend(
                [
                    "   No public implemented methods are currently available for this hazard family.",
                    "",
                ]
            )

        if experimental:
            tab_lines.extend(
                [
                    "   .. rubric:: {title}".format(title=EXPERIMENTAL_SECTION_TITLE),
                    "",
                    "   .. container:: catalog-section-note",
                    "",
                    "      {summary}".format(summary=EXPERIMENTAL_SECTION_SUMMARY),
                    "",
                ]
            )
            tab_lines.extend(_indent_lines(_render_model_grid(experimental, benchmark_links)))
        tab_lines.append("")
        lines.extend(_indent_lines(tab_lines))

    lines.extend(
        [
            "",
            "Recommended Entry Points",
            "------------------------",
            "",
            "If you are new to PyHazards, these four models provide the clearest",
            "starting point for each hazard family.",
            "",
        ]
    )
    lines.extend(_render_recommended_grid(public_cards, benchmark_links))

    lines.extend(
        [
            "",
            "Programmatic Use",
            "----------------",
            "",
            "Use :doc:`api/pyhazards.models` for the developer registry workflow,",
            "builder examples, and package-level API lookup. Use",
            ":doc:`pyhazards_benchmarks` to compare compatible benchmark families",
            "before selecting a model for evaluation.",
            "",
            ".. toctree::",
            "   :maxdepth: 1",
            "   :hidden:",
            "",
        ]
    )
    for card in public_cards:
        lines.append("   modules/{slug}".format(slug=card.module_doc_name))

    lines.append("")
    return "\n".join(lines)


def render_api_page(cards: Sequence[ModelCard]) -> str:
    grouped = group_cards_by_hazard(public_catalog_cards(cards))
    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "pyhazards.models package",
        "========================",
        "",
        "Catalog Summary",
        "---------------",
        "",
        "This page links the public model catalog, the developer registry",
        "workflow, and the package submodules used to implement model builders.",
        "",
        "For the curated browsing experience, use :doc:`/pyhazards_models`.",
        "",
    ]
    for hazard, hazard_cards in grouped.items():
        lines.extend([hazard, "~" * len(hazard), ""])
        cards_by_status = _cards_by_status(hazard_cards)
        implemented_cards = cards_by_status["core"] + cards_by_status["variant"]
        experimental_cards = cards_by_status["experimental"]
        lines.extend([IMPLEMENTED_SECTION_TITLE, "+" * len(IMPLEMENTED_SECTION_TITLE), ""])
        if not implemented_cards:
            lines.extend(
                [
                    "No public implemented methods are currently available for this hazard family.",
                    "",
                ]
            )
        else:
            links = ", ".join(_doc_link(card, absolute=True) for card in implemented_cards)
            lines.extend([links + ".", ""])

        if experimental_cards:
            lines.extend([EXPERIMENTAL_SECTION_TITLE, "+" * len(EXPERIMENTAL_SECTION_TITLE), ""])
            links = ", ".join(_doc_link(card, absolute=True) for card in experimental_cards)
            lines.extend([links + ".", ""])

    lines.extend(
        [
            "Developer Registry Workflow",
            "---------------------------",
            "",
            "Use this section when you need the package-level builder and registry",
            "interface rather than the public catalog presentation.",
            "",
            "Build a Registered Model",
            "~~~~~~~~~~~~~~~~~~~~~~~~",
            "",
            ".. code-block:: python",
            "",
            "    from pyhazards.models import build_model",
            "",
            "    model = build_model(",
            '        name="phasenet",',
            '        task="regression",',
            "        in_channels=3,",
            "    )",
            "",
            "Register a Custom Model",
            "~~~~~~~~~~~~~~~~~~~~~~~",
            "",
            ".. code-block:: python",
            "",
            "    import torch.nn as nn",
            "    from pyhazards.models import build_model, register_model",
            "",
            "    def my_custom_builder(task: str, in_dim: int, out_dim: int, **kwargs) -> nn.Module:",
            '        hidden = kwargs.get("hidden_dim", 128)',
            "        return nn.Sequential(",
            "            nn.Linear(in_dim, hidden),",
            "            nn.ReLU(),",
            "            nn.Linear(hidden, out_dim),",
            "        )",
            "",
            '    register_model("my_mlp", my_custom_builder, defaults={"hidden_dim": 128})',
            '    model = build_model(name="my_mlp", task="regression", in_dim=16, out_dim=1)',
            "",
            "Notes",
            "~~~~~",
            "",
            "- Builders receive ``task`` plus any kwargs you pass.",
            "- ``register_model`` stores optional defaults so configs can stay small.",
            "- Use :doc:`/implementation` for the full contributor workflow.",
            "",
            "Submodules",
            "----------",
            "",
            "pyhazards.models.backbones module",
            "----------------------------------",
            "",
            ".. automodule:: pyhazards.models.backbones",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.heads module",
            "------------------------------",
            "",
            ".. automodule:: pyhazards.models.heads",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.builder module",
            "-------------------------------",
            "",
            ".. automodule:: pyhazards.models.builder",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "pyhazards.models.registry module",
            "--------------------------------",
            "",
            ".. automodule:: pyhazards.models.registry",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
            "Module contents",
            "---------------",
            "",
            ".. automodule:: pyhazards.models",
            "   :members:",
            "   :undoc-members:",
            "   :show-inheritance:",
            "",
        ]
    )
    return "\n".join(lines)


def render_module_page(card: ModelCard) -> str:
    title = card.display_name
    benchmark_links = _benchmark_links_by_model()
    task_labels = _entry_task_labels(card, benchmark_links)
    benchmark_family = _entry_benchmark_family(card, benchmark_links, absolute=True)
    ecosystems = _entry_ecosystem_links(card, benchmark_links, absolute=True)
    lines: List[str] = [
        GENERATED_MARKER,
        "",
    ]
    if not card.include_in_public_catalog:
        lines.extend([":orphan:", ""])

    lines.extend(
        [
            title,
            "=" * len(title),
            "",
            "Overview",
            "--------",
            "",
            _single_line(card.description[0]),
            "",
            "At a Glance",
            "-----------",
            "",
            ".. grid:: 1 2 4 4",
            "   :gutter: 2",
            "   :class-container: catalog-grid",
            "",
        ]
    )
    lines.extend(
        _indent_lines(
            _stat_card("Hazard Family", _display_hazard_label(card.hazard), "Public catalog grouping used for this model.")
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card("Maturity", MATURITY_LABELS[card.catalog_status], "Catalog maturity label used on the index page.")
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card("Tasks", str(len(task_labels)), ", ".join(task_labels))
        )
    )
    lines.extend(
        _indent_lines(
            _stat_card(
                "Benchmark Family",
                benchmark_family or "Unmapped",
                "Primary benchmark-family link used for compatible evaluation coverage.",
            )
        )
    )
    lines.extend(
        [
            "",
            "Description",
            "-----------",
            "",
        ]
    )
    for paragraph in card.description:
        lines.append(_single_line(paragraph))
        lines.append("")

    lines.extend(
        [
            "Benchmark Compatibility",
            "-----------------------",
            "",
            "**Primary benchmark family:** {family}".format(
                family=benchmark_family or "Not yet mapped."
            ),
            "",
        ]
    )
    if ecosystems:
        lines.extend(
            [
                "**Mapped benchmark ecosystems:** {ecosystems}".format(
                    ecosystems=", ".join(ecosystems)
                ),
                "",
            ]
        )
    lines.extend(
        [
            "External References",
            "-------------------",
            "",
            _paper_links(card),
            "",
            "Registry Name",
            "-------------",
            "",
            "Primary entrypoint: ``{name}``".format(name=card.model_name),
            "",
        ]
    )

    if card.family_label:
        lines.append("Family grouping: ``{family}``".format(family=card.family_label))
        lines.append("")

    if card.aliases:
        lines.append("Aliases: {aliases}".format(
            aliases=", ".join("``{name}``".format(name=name) for name in card.aliases)
        ))
        lines.append("")

    lines.extend(
        [
            "Supported Tasks",
            "---------------",
            "",
        ]
    )
    for task in task_labels:
        lines.append("- {task}".format(task=task))
    lines.append("")
    lines.extend(
        [
            "Programmatic Use",
            "----------------",
            "",
            ".. code-block:: python",
            "",
            _indent_block(card.example),
            "",
        ]
    )

    if card.notes:
        lines.extend(["Notes", "-----", ""])
        for note in card.notes:
            lines.append("- {note}".format(note=note))
        lines.append("")

    return "\n".join(lines)


def rendered_docs(cards: Sequence[ModelCard]) -> Dict[Path, str]:
    targets: Dict[Path, str] = {
        MODEL_PAGE_PATH: render_model_page(cards),
        API_PAGE_PATH: render_api_page(cards),
    }
    for card in cards:
        targets[card.module_doc_path] = render_module_page(card)
    return targets


def sync_generated_docs(cards: Sequence[ModelCard], check: bool = False) -> List[Path]:
    changes: List[Path] = []
    targets = rendered_docs(cards)

    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changes.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    managed_paths = set(targets.keys())
    for path in MODULE_DOCS_DIR.glob("models_*.rst"):
        if path in managed_paths or not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        changes.append(path)
        if not check:
            path.unlink()

    return changes


def model_catalog_alignment_issues(cards: Sequence[ModelCard]) -> List[str]:
    from pyhazards.models import available_models

    issues: List[str] = []
    registered = set(available_models())
    for card in cards:
        for name in card.registry_names:
            if name not in registered:
                issues.append("Model '{name}' is documented but not registered.".format(name=name))
    return issues


def builder_contract_issues(card: ModelCard) -> List[str]:
    from pyhazards.models.registry import get_model_config

    issues: List[str] = []
    config = get_model_config(card.model_name)
    if config is None:
        return ["Model '{name}' is not registered.".format(name=card.model_name)]

    builder = config["builder"]
    if builder.__name__ != card.builder_name:
        issues.append(
            "Model card expects builder '{expected}' but registry uses '{actual}'.".format(
                expected=card.builder_name,
                actual=builder.__name__,
            )
        )

    params = inspect.signature(builder).parameters
    has_var_kwargs = any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD
        for parameter in params.values()
    )
    if "task" not in params and not has_var_kwargs:
        issues.append(
            "Builder '{name}' must accept a 'task' argument or **kwargs.".format(
                name=builder.__name__
            )
        )
    if not has_var_kwargs:
        issues.append(
            "Builder '{name}' should accept **kwargs for registry compatibility.".format(
                name=builder.__name__
            )
        )
    return issues


def source_contract_issues(card: ModelCard) -> List[str]:
    issues: List[str] = []
    if not card.source_path.exists():
        return [
            "Documented source file does not exist: {path}".format(path=card.source_file)
        ]

    source = card.source_path.read_text(encoding="utf-8")
    if "ValueError" not in source or ("shape" not in source and "ndim" not in source):
        issues.append(
            "Source file '{path}' should include explicit input-shape validation with a clear error.".format(
                path=card.source_file
            )
        )
    return issues


def _dtype_for_name(dtype_name: str) -> torch.dtype:
    if not hasattr(torch, dtype_name):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    dtype = getattr(torch, dtype_name)
    if not isinstance(dtype, torch.dtype):
        raise ValueError("Unsupported torch dtype in smoke test: {name}".format(name=dtype_name))
    return dtype


def _make_tensor(spec: SmokeTensorSpec) -> torch.Tensor:
    return torch.randn(*spec.shape, dtype=_dtype_for_name(spec.dtype))


def _prepare_smoke_input(spec: SmokeInputSpec) -> Any:
    kind = spec.kind.lower()
    if kind == "tensor":
        return _make_tensor(spec.tensor)
    if kind == "mapping":
        return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.mapping.items()}
    return {name: _make_tensor(tensor_spec) for name, tensor_spec in spec.kwargs.items()}


def _shape_of_output(output: Any) -> Any:
    if isinstance(output, torch.Tensor):
        return list(output.shape)
    if isinstance(output, (list, tuple)):
        return [_shape_of_output(item) for item in output]
    return type(output).__name__


def run_smoke_test(card: ModelCard) -> Dict[str, Any]:
    from pyhazards.models import build_model

    torch.manual_seed(0)
    model = build_model(
        name=card.model_name,
        task=card.smoke_test.task,
        **card.smoke_test.build_kwargs
    )
    model.eval()
    prepared = _prepare_smoke_input(card.smoke_test.input)
    with torch.no_grad():
        if card.smoke_test.input.kind.lower() == "tensor":
            output = model(prepared)
        elif card.smoke_test.input.kind.lower() == "mapping":
            output = model(prepared)
        else:
            output = model(**prepared)

    actual_shape = _shape_of_output(output)
    expected = card.smoke_test.expected_output
    if expected.kind.lower() == "tensor":
        ok = actual_shape == expected.shape
    else:
        ok = actual_shape == expected.shapes

    return {
        "ok": ok,
        "actual_shape": actual_shape,
        "expected_shape": expected.shape if expected.kind.lower() == "tensor" else expected.shapes,
        "summary": "{name}: output shape {actual}".format(
            name=card.model_name,
            actual=actual_shape,
        ),
    }


def touched_card_names(cards: Sequence[ModelCard], changed_files: Iterable[str]) -> List[str]:
    source_to_name = {
        str(card.source_file): card.model_name
        for card in cards
    }
    names: Set[str] = set()
    for path in changed_files:
        if path.startswith("pyhazards/model_cards/") and path.endswith((".yaml", ".yml")):
            names.add(Path(path).stem)
        if path in source_to_name:
            names.add(source_to_name[path])
    return sorted(name for name in names if name)
