name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10  # Use a valid Python version

      - name: Create Conda environment and install dependencies
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda create -n sphinx-env python=3.10 -y  # Correct Python version
          conda activate sphinx-env
          conda install -c conda-forge sphinx sphinx-rtd-theme -y

      - name: Build Sphinx documentation
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate sphinx-env
          sphinx-build -b html source build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
