name: Build and Deploy Sphinx Docs  # Workflow name

on:
  push:
    branches:
      - new  # Trigger workflow on pushes to the 'new' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3  # Clone the GitHub repo

      # Step 2: Install Miniconda
      - name: Set up Miniconda
        uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: false  # Disable automatic update to control it manually
          python-version: 3.10

      # Step 2.1: Update Conda manually
      - name: Update Conda
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda update -n base -c defaults conda -y
      
      # Step 3: Create Conda environment and install dependencies
      - name: Create Conda environment and install dependencies
        run: |
          conda create -n sphinx-env python=3.10 -y
          source ~/miniconda/etc/profile.d/conda.sh  # Ensure conda is loaded
          conda activate sphinx-env
          conda install -c conda-forge sphinx sphinx-rtd-theme -y

      # Step 4: Build the Sphinx documentation
      - name: Build Sphinx documentation
        run: |
          source ~/miniconda/etc/profile.d/conda.sh  # Ensure conda is loaded
          conda activate sphinx-env
          sphinx-build -b html source build/html

      # Step 5: Deploy the documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
